services:
  - type: web
    name: twitter-clone-app
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://twitter-clone-app-qnhp.onrender.com
